### ISSUE TITLE
Javascript - ne dela pravilno

### ISSUE THREAD

**Issue by SashaOslaj** [SashaOslaj/ZimskeOI#4]
Jaz in Tina imave problem, ker nama v datoteki rezultat.html ne dela javascript funkcija, sicer spletna stran za vrniti rezultate z določenimi parametri še ni dokončana (trenutno izpiše samo Hello). Gumb, ki bi nama moral vrniti to stran ne dela.

**Comment by jaanos** [comment]
Težava se pojavi, ker imata za ID-je izbirnikov `select-disciplino` in `select-poddisciplino`, medtem ko funkcija pričakuje podatke od `select-disciplina` in `select-poddisciplina` (razlika je v zadnji črki).

Svetujem sicer, da v URL-jih ne uporabljata imen, pač pa ID-je disciplin in poddisciplin (zadostoval bo torej slednji). ID-je lahko v `<select>` dasta pod `value`, v funkciji pa potem namesto `.text` uporabita `.value`.
